// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhJG3l4ijNvnRgoayVhrW7-GMP3Gibzcw',
    appId: '1:925162935539:web:fa7233ecb93cf2b7da1386',
    messagingSenderId: '925162935539',
    projectId: 'journey-to-balance',
    authDomain: 'journey-to-balance.firebaseapp.com',
    storageBucket: 'journey-to-balance.firebasestorage.app',
    measurementId: 'G-HZDCLX1LZF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5owrDaiJn5I-s4nDT2W-wui4qOLL-a4o',
    appId: '1:925162935539:android:58410c53c7e47196da1386',
    messagingSenderId: '925162935539',
    projectId: 'journey-to-balance',
    storageBucket: 'journey-to-balance.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu7q-Vm1-BFMkKPSuMYqO7tToiO37AK0s',
    appId: '1:925162935539:ios:a3d143a395d7ab5eda1386',
    messagingSenderId: '925162935539',
    projectId: 'journey-to-balance',
    storageBucket: 'journey-to-balance.firebasestorage.app',
    iosClientId: '925162935539-ikfmq3ubbhdp98v56qnemct0ntjsvgsm.apps.googleusercontent.com',
    iosBundleId: 'com.example.justBudget',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCu7q-Vm1-BFMkKPSuMYqO7tToiO37AK0s',
    appId: '1:925162935539:ios:a3d143a395d7ab5eda1386',
    messagingSenderId: '925162935539',
    projectId: 'journey-to-balance',
    storageBucket: 'journey-to-balance.firebasestorage.app',
    iosClientId: '925162935539-ikfmq3ubbhdp98v56qnemct0ntjsvgsm.apps.googleusercontent.com',
    iosBundleId: 'com.example.justBudget',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhJG3l4ijNvnRgoayVhrW7-GMP3Gibzcw',
    appId: '1:925162935539:web:92ae3e73ab3a4e91da1386',
    messagingSenderId: '925162935539',
    projectId: 'journey-to-balance',
    authDomain: 'journey-to-balance.firebaseapp.com',
    storageBucket: 'journey-to-balance.firebasestorage.app',
    measurementId: 'G-P8P1QN8QMX',
  );
}
